# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "bookshelf"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# template: "simple"

template: "template_toolkit"
engines:
   template_toolkit:
     views: 'D:\\tmp\\bookshelf\\views'
#     start_tag: '[%'
#     end_tag:   '%]'

# For session support enable the following line and see Dancer::Session
# session: "YAML"

plugins:
  Database:
    bookshelf:
#      dsn: dbi:mysql:dbname=bookshelf
      dbname: 'dbi:mysql:dbname=bookshell'
      database: 'bookshell'
      driver: 'mysql'
      host: 'localhost'
      port: 3306
      username: 'root'
      password: '1234'
      connection_check_threshold: 10
      dbi_params:
          RaiseError: 1
          AutoCommit: 1
      on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]

serializer: JSON
